import {
  ArrowRight,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleHelp,
  Clock,
  Dumbbell,
  Globe,
  Leaf,
  Mail,
  MapPin,
  Menu,
  Play,
  Search,
  Send,
  ShoppingCart,
  SlidersHorizontal,
  Smartphone,
  Sprout,
  User,
  Users,
  Video,
  X,
  type LucideIcon,
} from "lucide-react";

export const iconMap: Record<string, LucideIcon> = {
  search: Search,
  menu: Menu,
  close: X,
  shopping_cart: ShoppingCart,
  add_shopping_cart: ShoppingCart,
  arrow_forward: ArrowRight,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  expand_less: ChevronUp,
  expand_more: ChevronDown,
  play_arrow: Play,
  check_circle: CheckCircle,
  video_camera_front: Video,
  groups: Users,
  person: User,
  phone_iphone: Smartphone,
  schedule: Clock,
  spa: Leaf,
  fitness_center: Dumbbell,
  energy_savings_leaf: Sprout,
  tune: SlidersHorizontal,
  public: Globe,
  alternate_email: Mail,
  near_me: MapPin,
  send: Send,
};

export function resolveIcon(name: string): LucideIcon {
  return iconMap[name] ?? CircleHelp;
}
